// Machine code generated by CMPE220 Assembler
// Total instructions: 11

word_t program[] = {
    0x1000,  // [0] MOV R0, 0        ; R0 = 0 (counter)
    0x120A,  // [1] MOV R1, 10       ; R1 = 10 (limit)
    0x1420,  // [2] MOV R2, 32       ; R2 = 32 (I/O port address for character output)
    0x1630,  // [3]     MOV R3, 48       ; R3 = ASCII '0' (48)
    0x263F,  // [4]     ADD R3, R0       ; R3 = R3 + R0 (compute ASCII character)
    0x2001,  // [5]     ADD R0, 1        ; R0 = R0 + 1
    0x383F,  // [6]     SUB R4, R0       ; R4 = R0 (copy for comparison)
    0x383F,  // [7]     SUB R4, R1       ; R4 = R0 - R1
    0x900A,  // [8]     JZ done          ; Jump if zero flag is set
    0x8003,  // [9]     JMP loop
    0xC000  // [10]     HALT             ; Stop execution
};

int program_size = 11;
