// run_timer.c
// Demo driver to run the timer.asm program on the software CPU

#include <stdio.h>
#include <stdint.h>

// ⚠️ Match whatever your other demo files use:
// If run_hello.c does #include "cpu.c", do the same here.
// If it does #include "cpu.h", change this to "cpu.h".
#include "cpu.c"

// This is generated by: ./assembler ../Assembly_programs/timer.asm timer.h
#include "timer.h"

// ---------------------------------------------------------------------------
// STEP 1: Match these signatures to whatever you already use in run_hello.c
//         and run_fibonacci.c.
// ---------------------------------------------------------------------------

// If your project uses a CPU struct, you probably have something like:
//
//   extern struct CPU cpu;
//   void cpu_reset(void);
//   void cpu_step(void);
//   int cpu_is_halted(void);
//   void cpu_load_program(const uint16_t *prog, size_t size, uint16_t start_ip);
//
// Go open run_fibonacci.c and copy the exact function calls & types it uses.
// Then update these declarations if needed.

extern struct CPU cpu;   // remove or adjust if your CPU is global in a different way

void cpu_reset(void);
void cpu_step(void);
int  cpu_is_halted(void);
void cpu_load_program(const uint16_t *prog, size_t size, uint16_t start_ip);

// From timer.h (check the actual names inside that file after you generate it)
extern const uint16_t TIMER_PROGRAM[];
extern const size_t   TIMER_PROGRAM_SIZE;

// ---------------------------------------------------------------------------
// Optional: print CPU state each instruction to show Fetch/Compute/Store cycles
// Adjust field names (ip, ir, regs, flags) to match your cpu.c.
// If this is too much work, you can comment out this function + its call.
// ---------------------------------------------------------------------------

static void print_cpu_state(int cycle)
{
    printf("Cycle %4d | IP=0x%04X  IR=0x%04X  R0=0x%04X  Z=%d N=%d C=%d\n",
           cycle,
           cpu.ip,        // change if your instruction pointer has a different name
           cpu.ir,        // change if your instruction register has a different name
           cpu.regs[0],   // change if your register array is named differently
           cpu.flags.Z,   // change to your actual flag fields
           cpu.flags.N,
           cpu.flags.C);
}

int main(void)
{
    printf("==== TIMER PROGRAM DEMO ====\n");

    // 1. Reset / initialize CPU (same call as run_hello.c / run_fibonacci.c)
    cpu_reset();

    // 2. Load timer program into memory at address 0x0000 or your default
    cpu_load_program(TIMER_PROGRAM, TIMER_PROGRAM_SIZE, 0x0000);

    printf("Running timer program...\n\n");
    printf("Cycle | IP     IR     R0     Z N C\n");
    printf("------+-------------------------------\n");

    int cycle = 0;

    // 3. Step until HALT, printing state each instruction
    while (!cpu_is_halted()) {
        print_cpu_state(cycle);
        cpu_step();
        cycle++;
    }

    printf("\nProgram halted after %d cycles.\n", cycle);
    printf("==== END TIMER DEMO ====\n");

    return 0;
}
